version: '3.1'
services:
  app:
    container_name: currencyexchanger
    image: docker-currencies8
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgrepass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
